/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BAM.glb -o src/components/BAM.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BAM(props) {
  const { nodes, materials } = useGLTF("/models/BAM.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_6c4d6c96"
        geometry={nodes.tripo_node_6c4d6c96.geometry}
        material={materials.tripo_mat_6c4d6c96}
      />
    </group>
  );
}

useGLTF.preload("/models/BAM.glb");
