/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CAR.glb -o src/components/CAR.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CAR(props) {
  const { nodes, materials } = useGLTF("/models/CAR.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_30537520"
        geometry={nodes.tripo_node_30537520.geometry}
        material={materials.tripo_mat_30537520}
      />
    </group>
  );
}

useGLTF.preload("/models/CAR.glb");
