/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Famaly.glb -o src/components/Famaly.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Famaly(props) {
  const { nodes, materials } = useGLTF("/models/Famaly.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_be6065b7"
        geometry={nodes.tripo_node_be6065b7.geometry}
        material={materials.tripo_mat_be6065b7}
      />
    </group>
  );
}

useGLTF.preload("/models/Famaly.glb");
