/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Latarka_MAPA.glb -o src/components/Latarka_MAPA.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Latarka_MAPA(props) {
  const { nodes, materials } = useGLTF("/models/Latarka_MAPA.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_fde78407"
        geometry={nodes.tripo_node_fde78407.geometry}
        material={materials.tripo_mat_fde78407}
      />
    </group>
  );
}

useGLTF.preload("/models/Latarka_MAPA.glb");
