/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Mapa_Pineska_Duza.glb -o src/components/Mapa_Pineska_Duza.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Mapa_Pineska_Duza(props) {
  const { nodes, materials } = useGLTF("/models/Mapa_Pineska_Duza.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_8c2dcf7b"
        geometry={nodes.tripo_node_8c2dcf7b.geometry}
        material={materials.tripo_mat_8c2dcf7b}
      />
    </group>
  );
}

useGLTF.preload("/models/Mapa_Pineska_Duza.glb");
