/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/MapaPineska.glb -o src/components/MapaPineska.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MapaPineska(props) {
  const { nodes, materials } = useGLTF("/models/MapaPineska.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_2f92d493"
        geometry={nodes.tripo_node_2f92d493.geometry}
        material={materials.tripo_mat_2f92d493}
        position={[0, 0.297, -0.078]}
        rotation={[0.094, 0, -1.185]}
      />
      <mesh
        name="tripo_node_2f92d493001"
        geometry={nodes.tripo_node_2f92d493001.geometry}
        material={materials.tripo_mat_2f92d493}
      />
    </group>
  );
}

useGLTF.preload("/models/MapaPineska.glb");
