/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PetrolStation.glb -o src/components/PetrolStation.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PetrolStation(props) {
  const { nodes, materials } = useGLTF("/models/PetrolStation.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_29607fc4"
        geometry={nodes.tripo_node_29607fc4.geometry}
        material={materials.tripo_mat_29607fc4}
      />
    </group>
  );
}

useGLTF.preload("/models/PetrolStation.glb");
