/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PytanieZolte.glb -o src/components/PytanieZolte.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PytanieZolte(props) {
  const { nodes, materials } = useGLTF("/models/PytanieZolte.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tripo_node_5ae3840f"
        geometry={nodes.tripo_node_5ae3840f.geometry}
        material={materials.tripo_mat_5ae3840f}
      />
    </group>
  );
}

useGLTF.preload("/models/PytanieZolte.glb");
