/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Znak_Zapytania.glb -o src/components/Znak_Zapytania.jsx -k -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Znak_Zapytania(props) {
  const { nodes, materials } = useGLTF("/models/Znak_Zapytania.glb");
  const ref = useRef();

  // Obracanie w osi Y
  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.y += 0.06;
    }
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        name="tripo_node_4ef3e56b"
        geometry={nodes.tripo_node_4ef3e56b.geometry}
        material={materials.tripo_mat_4ef3e56b}
      />
    </group>
  );
}

useGLTF.preload("/models/Znak_Zapytania.glb");
